apiVersion: apps/v1
kind: Deployment
metadata:
  name: robinson-eks-registry
spec:
  replicas: 3
  selector:
    matchLabels:
      app: robinson-eks-registry
  template:
    metadata:
      labels:
        app: robinson-eks-registry
    spec:
      containers:
        - name: robinson-eks-registry
          image: <DOCKER_IMAGE_URI>
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: robinson-eks-registry-service
spec:
  selector:
    app: robinson-eks-registry
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer